language: php
php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - phpize
    - ./configure
    - make
    - echo "extension = decorators.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: make test
